SPOOL create_widgets_tables_AS.txt

SELECT TO_CHAR(SYSDATE,'DD-MON-YYYY HH24:MI:SS'), USER, NAME
FROM v$database;

CREATE TABLE DEPARTMENTS(
    dept_id NUMBER(5) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 5,
    dept_name VARCHAR2(50) NOT NULL,
    dept_location VARCHAR2(50) NOT NULL,
    PRIMARY KEY(dept_id));

CREATE TABLE EMPLOYEES(
    emp_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 90011,
    emp_entered_by VARCHAR2(50) NOT NULL,
    emp_date_entered DATE NOT NULL,
    emp_surname VARCHAR2(50) NOT NULL,
    emp_first_name VARCHAR2(50) NOT NULL,
    emp_job_title VARCHAR2(50) NOT NULL,
    emp_manager_id NUMBER(10) NOT NULL,
    emp_date_hired DATE NOT NULL,
    emp_salary NUMBER(10),
    emp_dept_id NUMBER(5),
    emp_date_expired DATE,
    emp_expired_by VARCHAR2(50),
    PRIMARY KEY(emp_id));
    

--CREATE PUBLIC SYNONYM DEPARTMENTS for LIVE.DEPARTMENTS;
--CREATE PUBLIC SYNONYM EMPLOYEES for LIVE.EMPLOYEES;
--
GRANT SELECT on DEPARTMENTS to PUBLIC;
--GRANT ALL on DEPARTMENTS to ‘Some Roles’;
GRANT SELECT on EMPLOYEES to PUBLIC;
--GRANT ALL on EMPLOYEES to ‘Some Roles’;

DESC EMPLOYEES;
DESC DEPARTMENTS;                
                
                
PROMPT Commit data then spool off.....                
                
SPOOL OFF
                
